### PR TITLE
Add renderingMiddlewareProps.receivedMessageAnchorStyles.filter

### PR DESCRIPTION
**Pull request by rangerz**
as title

### CODE REVIEW

**Comment by charliewang95** [comment]
The file you're modifying is not used in production code, and is for documentation only. Is this file what you're trying to edit? https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/webchatcontainerstateful/webchatcontroller/middlewares/renderingmiddlewares/defaultStyles/defaultReceivedMessageAnchorStyles.ts

**Comment by charliewang95** [comment]
Also please create a fork to raise PRs, instead of using the microsoft fork directly

**Comment by rangerz** [comment]
> The file you're modifying is not used in production code, and is for documentation only. Is this file what you're trying to edit? https://github.com/microsoft/omnichannel-chat-widget/blob/main/chat-widget/src/components/webchatcontainerstateful/webchatcontroller/middlewares/renderingmiddlewares/defaultStyles/defaultReceivedMessageAnchorStyles.ts

Yes, it's for documents only
https://github.com/microsoft/omnichannel-chat-widget/blob/1f4a6a789d478a25684ce910a65deaf0089da6b7/chat-widget/src/components/webchatcontainerstateful/WebChatContainerStateful.tsx#L159

**Comment by charliewang95** [comment]
This file will be deleted as part of the documentation upgrade in this PR #285 

I've modified the defaultReceivedMessageAnchorStyles file to include "filter" instead of inline, so this doc update is not needed

**Pull request closed without merging**
